apiVersion: apps/v1
kind: Deployment
metadata:
  name: lychee
  namespace: lychee
  labels:
    app: lychee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lychee
  template:
    metadata:
      labels:
        app: lychee
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lychee
      initContainers:
      - name: permission-fix
        image: busybox
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Fixing permissions"
          chmod -R 777 /data
          mkdir -p /data/uploads/big
          mkdir -p /data/uploads/medium
          mkdir -p /data/uploads/thumb
          chown www-data:www-data /data/uploads
          chown www-data:www-data /data/uploads/big
          chown www-data:www-data /data/uploads/medium
          chown www-data:www-data /data/uploads/thumb
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - image: 'kdelfour/lychee-docker'
        imagePullPolicy: 'Always'
        name: lychee
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2000m
            memory: 4G
          requests:
            cpu: 100m
            memory: 128m
        volumeMounts:
        - name: data
          mountPath: "/data"
          subPath: "data"
        - name: data
          mountPath: "/uploads"
          subPath: "uploads"
        - name: data
          mountPath: "/mysql"
          subPath: "mysql"
