apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lychee
  labels:
    app: lychee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lychee
  serviceName: lychee
  volumeClaimTemplates:
  - metadata:
      name: uploads
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  template:
    metadata:
      labels:
        app: lychee
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: 'lycheeorg/lychee:v4.4.0'
        imagePullPolicy: 'Always'
        name: lychee
        ports:
        - containerPort: 80
        volumeMounts:
        - name: uploads
          mountPath: "/uploads"
          subPath: "uploads"
        resources:
          limits:
            cpu: 2000m
            memory: 4G
          requests:
            cpu: 100m
            memory: 128m
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 60
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 60
          failureThreshold: 10
        env:
        - name: PHP_TZ
          value: America/New_York
        - name: DB_CONNECTION
          value: mysql
        - name: DB_DATABASE
          value: lychee
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: {{ .Values.mysql.db.password }}
        - name: DB_PORT
          value: "3306"
        - name: DB_HOST
          value: {{ .Values.mysql.mysqlHost | default (printf "%s-%s" .Release.Name "mysql") }}
