apiVersion: v1
kind: Service
metadata:
  name: lychee
  labels:
    app: lychee
spec:
  ports:
  - name: dashboard
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lychee
  type: ClusterIP

