apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: hackmd
spec:
  persistentVolumeClaim:
    claimName: hackmd
  schedule:
    - every: day
      keep: 1
    - every: week
      keep: 1
    - every: month
      keep: 1
---
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: hackmd-postgresql
spec:
  persistentVolumeClaim:
    claimName: hackmd-postgresql
  schedule:
    - every: day
      keep: 1
    - every: week
      keep: 1
    - every: month
      keep: 1

