apiVersion: photon.fairwinds.com/v1
kind: SnapshotGroup
metadata:
  name: hackmd
  namespace: notepad
spec:
  claim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  schedule:
    - every: day
      keep: 1
    - every: week
      keep: 1
    - every: month
      keep: 3
---
apiVersion: photon.fairwinds.com/v1
kind: SnapshotGroup
metadata:
  name: hackmd-postgresql
  namespace: notepad
spec:
  claim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  schedule:
    - every: day
      keep: 1
    - every: week
      keep: 1
    - every: month
      keep: 3

