apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  name: polaris
  namespace: polaris
spec:
  rules:
    - host: polaris.rocketops.io
      http:
        paths:
          - backend:
              serviceName: polaris-dashboard
              servicePort: 8080
            path: /
    - host: polaris.rbren.io
      http:
        paths:
          - backend:
              serviceName: polaris-dashboard
              servicePort: 8080
            path: /
  tls:
  - secretName: tls-prod-cert
    hosts:
    - polaris.rocketops.io
    - polaris.rbren.io
