kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lychee
  labels:
    app: lychee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: "local-path"

