apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bobby.brennan@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
