apiVersion: v1
kind: Namespace
metadata:
  name: github-notifs
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: github-notifs
  namespace: github-notifs
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: github-notif
            image: ubuntu:18.04
            command: ["bash"]
            args:
            - -c
            - |
              last_min=$(date -u +"%Y-%m-%dT%H:%M:%SZ" --date="-1 minute")
              apt-get update && apt-get install -y curl jq
              curl --fail -H "Authorization: Bearer $GITHUB_TOKEN" \
                  "https://api.github.com/notifications?since=$last_min" > notifs.json
              cat notifs.json

              for row in $(cat notifs.json | jq -r '.[] | @base64'); do
                  json=$(echo ${row} | base64 --decode)
                  reason=$(echo $json | jq -r ".reason")
                  echo "reason: $reason"
                  if [ $reason == "mention" ]; then
                    echo "$id    title: $title"
                    payload=$(echo $json | jq '{text: (.subject.title + " - " + .subject.latest_comment_url)}' )
                    curl -X POST -H 'Content-type: application/json' \
                      --data "${payload}" "https://hooks.slack.com/services/$SLACK_WEBHOOK_ID"
                  else
                    echo "skipping $reason"
                  fi
              done
            env:
            - name: SLACK_WEBHOOK_ID
              valueFrom:
                secretKeyRef:
                  name: slack-webhook-id
                  key: slack-webhook-id
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: github-token


