apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: ghost-app
spec:
  persistentVolumeClaim:
    claimName: ghost-app
  schedule:
    - every: day
      keep: 1
    - every: week
      keep: 1
    - every: month
      keep: 1
---
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: ghost-mariadb
spec:
  persistentVolumeClaim:
    claimName: ghost-mariadb
  schedule:
    - every: day
      keep: 1
    - every: week
      keep: 1
    - every: month
      keep: 1

